###
# Copyright (2016-2021) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
- hosts: all
  vars:
    config: "{{ playbook_dir }}/oneview_config.json"
    contents: "{{lookup('file', config)}}"
    hypervisor_manager_name: '172.18.13.11'
  tasks:
    - name: Create a Hypervisor Manager
      oneview_hypervisor_manager:
        config: "{{ config }}"
        state: present
        data:
          name: "{{ hypervisor_manager_name }}"
          displayName: 'vcenter'
          hypervisorType: 'Vmware'
          username: "{{ contents.hypervisor_manager_username }}"
          password: "{{ contents.hypervisor_manager_password }}"
      delegate_to: localhost
      register: hyp_mgr_1

    - name: Do nothing with the Hypervisor Manager when no changes are provided
      oneview_hypervisor_manager:
        config: "{{ config }}"
        state: present
        data:
          name: "{{ hypervisor_manager_name }}"
          displayName: 'vcenter'
          hypervisorType: 'Vmware'
      delegate_to: localhost

    - name: Update the Hypervisor Manager changing the attribute displayName
      oneview_hypervisor_manager:
        config: "{{ config }}"
        state: present
        data:
          name: "{{ hypervisor_manager_name }}"
          displayName: 'vcenter renamed'
          hypervisorType: 'Vmware'
          username: 'dcs'
          password: 'dcs'
      delegate_to: localhost

    - name: Delete the Hypervisor Manager
      oneview_hypervisor_manager:
        config: "{{ config }}"
        state: absent
        data: "{{ hyp_mgr_1.ansible_facts.hypervisor_manager }}"
      delegate_to: localhost
      register: deleted

    - name: Do nothing when Hypervisor Manager is absent
      oneview_hypervisor_manager:
        config: "{{ config }}"
        state: absent
        data: "{{ hyp_mgr_1.ansible_facts.hypervisor_manager }}"
      delegate_to: localhost
      register: deleted

    - name: Gather facts about a Server Certificate by remote address
      oneview_certificates_server_facts:
        config: "{{ config }}"
        remote: "{{ hypervisor_manager_name }}"
      delegate_to: localhost

    - set_fact:
        certificate: "{{ remote_certificate['certificateDetails'][0]['base64Data'] }}"

    - name: Re-create a Server Certificate
      oneview_certificates_server:
        config: "{{ config }}"
        state: present
        name: "{{ hypervisor_manager_name }}"
        data:
          certificateDetails:
            - aliasName: "{{ hypervisor_manager_name }}"
              base64Data: "{{ certificate }}"
      delegate_to: localhost
      register: svr_cert

    - name: Re-create a Hypervisor Manager to ensure continuity for automation script
      oneview_hypervisor_manager:
        config: "{{ config }}"
        state: present
        data:
          name: "{{ hypervisor_manager_name }}"
          displayName: 'vcenter'
          hypervisorType: 'Vmware'
          username: 'dcs'
          password: 'dcs'
      delegate_to: localhost
      register: hyp_mgr_1
